/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Result, } from "./components/game-minesweeper/models/result.model";
export namespace Components {
    interface GameMinesweeper {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLGameMinesweeperElement extends Components.GameMinesweeper, HTMLStencilElement {
    }
    var HTMLGameMinesweeperElement: {
        prototype: HTMLGameMinesweeperElement;
        new (): HTMLGameMinesweeperElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "game-minesweeper": HTMLGameMinesweeperElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface GameMinesweeper {
        "onLose"?: (event: CustomEvent<Result>) => void;
        "onWin"?: (event: CustomEvent<Result>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "game-minesweeper": GameMinesweeper;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "game-minesweeper": LocalJSX.GameMinesweeper & JSXBase.HTMLAttributes<HTMLGameMinesweeperElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
